name: Deploy web app to Azure Static Web Apps
on:
  push:
    branches:
      - latest_branch

permissions:
  issues: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.1
          cache: "npm"
      - name: npm install and npm build
        run: |
          npm install
          npm run build
      - name: npm run lint
        run: npm run lint
      - name: npm test
        run: npm run test -- --coverage 2>&1 | tee test_run_output.txt
      - name: Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZUREPRODWEBAPPAPITOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: /build
          skip_app_build: true
